-- 1. Tabla ROL
CREATE TABLE FIDE_ROL_TB (
    id_rol NUMBER,
    nombre VARCHAR2(100) NOT NULL,
    CONSTRAINT FIDE_ROL_ID_ROL_PK PRIMARY KEY (id_rol)
);
-- 2. Tabla USUARIO
CREATE TABLE FIDE_USUARIO_TB (
    id_usuario NUMBER,
    nombre VARCHAR2(100) NOT NULL,
    correo VARCHAR2(150) UNIQUE NOT NULL,
    contrasena VARCHAR2(150) NOT NULL,
    id_rol NUMBER,
    CONSTRAINT FIDE_USUARIO_ID_USUARIO_PK PRIMARY KEY (id_usuario),
    CONSTRAINT FIDE_USUARIO_ID_ROL_FK FOREIGN KEY (id_rol) REFERENCES FIDE_ROL_TB(id_rol)
);
-- 3. Tabla CATEGORIA
CREATE TABLE FIDE_CATEGORIA_TB (
    id_categoria NUMBER,
    nombre VARCHAR2(100) NOT NULL,
    CONSTRAINT FIDE_CATEGORIA_ID_CATEGORIA_PK PRIMARY KEY (id_categoria)
);
-- 4. Tabla UNIDAD_MEDIDA
CREATE TABLE FIDE_UNIDAD_MEDIDA_TB (
    id_unidad_medida NUMBER,
    nombre VARCHAR2(100) NOT NULL,
    CONSTRAINT FIDE_UNIDAD_MEDIDA_ID_UNIDAD_MEDIDA_PK PRIMARY KEY (id_unidad_medida)
);
-- 5. Tabla PRODUCTO
CREATE TABLE FIDE_PRODUCTO_TB (
    id_producto NUMBER,
    nombre VARCHAR2(100) NOT NULL,
    descripcion VARCHAR2(255),
    precio NUMBER(10,2) NOT NULL,
    id_categoria NUMBER,
    id_unidad_medida NUMBER,
    CONSTRAINT FIDE_PRODUCTO_ID_PRODUCTO_PK PRIMARY KEY (id_producto),
    CONSTRAINT FIDE_PRODUCTO_ID_CATEGORIA_FK FOREIGN KEY (id_categoria) REFERENCES FIDE_CATEGORIA_TB(id_categoria),
    CONSTRAINT FIDE_PRODUCTO_ID_UNIDAD_FK FOREIGN KEY (id_unidad_medida) REFERENCES FIDE_UNIDAD_MEDIDA_TB(id_unidad_medida)
);
-- 6. Tabla CLIENTE
CREATE TABLE FIDE_CLIENTE_TB (
    id_cliente NUMBER,
    nombre VARCHAR2(100) NOT NULL,
    correo VARCHAR2(150) UNIQUE,
    telefono VARCHAR2(15),
    CONSTRAINT FIDE_CLIENTE_ID_CLIENTE_PK PRIMARY KEY (id_cliente)
);
-- 7. Tabla DIRECCION
CREATE TABLE FIDE_DIRECCION_TB (
    id_direccion NUMBER,
    id_cliente NUMBER,
    direccion VARCHAR2(255) NOT NULL,
    CONSTRAINT FIDE_DIRECCION_ID_DIRECCION_PK PRIMARY KEY (id_direccion),
    CONSTRAINT FIDE_DIRECCION_ID_CLIENTE_FK FOREIGN KEY (id_cliente) REFERENCES FIDE_CLIENTE_TB(id_cliente)
);
-- 8. Tabla PROVINCIA
CREATE TABLE FIDE_PROVINCIA_TB (
    id_provincia NUMBER,
    nombre VARCHAR2(100) NOT NULL,
    CONSTRAINT FIDE_PROVINCIA_ID_PROVINCIA_PK PRIMARY KEY (id_provincia)
);
-- 9. Tabla CANTON
CREATE TABLE FIDE_CANTON_TB (
    id_canton NUMBER,
    id_provincia NUMBER,
    nombre VARCHAR2(100) NOT NULL,
    CONSTRAINT FIDE_CANTON_ID_CANTON_PK PRIMARY KEY (id_canton),
    CONSTRAINT FIDE_CANTON_ID_PROVINCIA_FK FOREIGN KEY (id_provincia) REFERENCES FIDE_PROVINCIA_TB(id_provincia)
);
-- 10. Tabla DISTRITO
CREATE TABLE FIDE_DISTRITO_TB (
    id_distrito NUMBER,
    id_canton NUMBER,
    nombre VARCHAR2(100) NOT NULL,
    CONSTRAINT FIDE_DISTRITO_ID_DISTRITO_PK PRIMARY KEY (id_distrito),
    CONSTRAINT FIDE_DISTRITO_ID_CANTON_FK FOREIGN KEY (id_canton) REFERENCES FIDE_CANTON_TB(id_canton)
);
-- 11. Tabla ESTADO_PEDIDO
CREATE TABLE FIDE_ESTADO_PEDIDO_TB (
    id_estado NUMBER,
    nombre VARCHAR2(100) NOT NULL,
    CONSTRAINT FIDE_ESTADO_PEDIDO_ID_ESTADO_PK PRIMARY KEY (id_estado)
);
-- 12. Tabla PEDIDO
CREATE TABLE FIDE_PEDIDO_TB (
    id_pedido NUMBER,
    fecha_pedido DATE NOT NULL,
    cantidad NUMBER NOT NULL,
    precio_unitario NUMBER(10,2) NOT NULL,
    subtotal NUMBER(10,2) NOT NULL,
    total NUMBER(10,2) NOT NULL,
    id_factura NUMBER,
    id_producto NUMBER,
    id_estado NUMBER,
    id_usuario NUMBER,
    id_cliente NUMBER,
    id_direccion NUMBER,
    CONSTRAINT FIDE_PEDIDO_ID_PEDIDO_PK PRIMARY KEY (id_pedido),
    CONSTRAINT FIDE_PEDIDO_ID_PRODUCTO_FK FOREIGN KEY (id_producto) REFERENCES FIDE_PRODUCTO_TB(id_producto),
    CONSTRAINT FIDE_PEDIDO_ID_ESTADO_FK FOREIGN KEY (id_estado) REFERENCES FIDE_ESTADO_PEDIDO_TB(id_estado),
    CONSTRAINT FIDE_PEDIDO_ID_USUARIO_FK FOREIGN KEY (id_usuario) REFERENCES FIDE_USUARIO_TB(id_usuario),
    CONSTRAINT FIDE_PEDIDO_ID_CLIENTE_FK FOREIGN KEY (id_cliente) REFERENCES FIDE_CLIENTE_TB(id_cliente),
    CONSTRAINT FIDE_PEDIDO_ID_DIRECCION_FK FOREIGN KEY (id_direccion) REFERENCES FIDE_DIRECCION_TB(id_direccion)
);
-- 13. Tabla INGRESO
CREATE TABLE FIDE_INGRESO_TB (
    id_ingreso NUMBER,
    id_producto NUMBER,
    cantidad NUMBER NOT NULL,
    fecha DATE NOT NULL,
    CONSTRAINT FIDE_INGRESO_ID_INGRESO_PK PRIMARY KEY (id_ingreso),
    CONSTRAINT FIDE_INGRESO_ID_PRODUCTO_FK FOREIGN KEY (id_producto) REFERENCES FIDE_PRODUCTO_TB(id_producto)
);
-- 14. Tabla EGRESO
CREATE TABLE FIDE_EGRESO_TB (
    id_egreso NUMBER,
    id_producto NUMBER,
    cantidad NUMBER NOT NULL,
    fecha DATE NOT NULL,
    CONSTRAINT FIDE_EGRESO_ID_EGRESO_PK PRIMARY KEY (id_egreso),
    CONSTRAINT FIDE_EGRESO_ID_PRODUCTO_FK FOREIGN KEY (id_producto) REFERENCES FIDE_PRODUCTO_TB(id_producto)
);
-- 15. Tabla INSUMO
CREATE TABLE FIDE_INSUMO_TB (
    id_insumo NUMBER,
    nombre VARCHAR2(100) NOT NULL,
    descripcion VARCHAR2(255),
    id_unidad_medida NUMBER,
    CONSTRAINT FIDE_INSUMO_ID_INSUMO_PK PRIMARY KEY (id_insumo),
    CONSTRAINT FIDE_INSUMO_ID_UNIDAD_FK FOREIGN KEY (id_unidad_medida) REFERENCES FIDE_UNIDAD_MEDIDA_TB(id_unidad_medida)
);
-- 16. Tabla PROVEEDOR
CREATE TABLE FIDE_PROVEEDOR_TB (
    id_proveedor NUMBER,
    nombre VARCHAR2(100) NOT NULL,
    correo VARCHAR2(150) UNIQUE,
    telefono VARCHAR2(15),
    CONSTRAINT FIDE_PROVEEDOR_ID_PROVEEDOR_PK PRIMARY KEY (id_proveedor)
);
-- 17. Tabla ORDEN_COMPRA
CREATE TABLE FIDE_ORDEN_COMPRA_TB (
    id_orden_compra NUMBER,
    id_proveedor NUMBER,
    fecha DATE NOT NULL,
    total NUMBER(10,2) NOT NULL,
    CONSTRAINT FIDE_ORDEN_COMPRA_ID_ORDEN_COMPRA_PK PRIMARY KEY (id_orden_compra),
    CONSTRAINT FIDE_ORDEN_COMPRA_ID_PROVEEDOR_FK FOREIGN KEY (id_proveedor) REFERENCES FIDE_PROVEEDOR_TB(id_proveedor)
);
-- 18. Tabla PRODUCTO_INSUMO
CREATE TABLE FIDE_PRODUCTO_INSUMO_TB (
    id_producto_insumo NUMBER,
    id_producto NUMBER,
    id_insumo NUMBER,
    CONSTRAINT FIDE_PRODUCTO_INSUMO_ID_PRODUCTO_INSUMO_PK PRIMARY KEY (id_producto_insumo),
    CONSTRAINT FIDE_PRODUCTO_INSUMO_ID_PRODUCTO_FK FOREIGN KEY (id_producto) REFERENCES FIDE_PRODUCTO_TB(id_producto),
    CONSTRAINT FIDE_PRODUCTO_INSUMO_ID_INSUMO_FK FOREIGN KEY (id_insumo) REFERENCES FIDE_INSUMO_TB(id_insumo)
);
-- 19. Tabla TIPO_EDIFICIO
CREATE TABLE FIDE_TIPO_EDIFICIO_TB (
    id_tipo_edificio NUMBER,
    nombre VARCHAR2(100) NOT NULL,
    CONSTRAINT FIDE_TIPO_EDIFICIO_ID_TIPO_EDIFICIO_PK PRIMARY KEY (id_tipo_edificio)
);
-- 20. Tabla MESA
CREATE TABLE FIDE_MESA_TB (
    ID_MESA NUMBER(10) PRIMARY KEY,
    NUMERO_MESA NUMBER(3) NOT NULL,
    CAPACIDAD NUMBER(3) NOT NULL,
    UBICACION VARCHAR2(50) NOT NULL
);



