-- 1. Tabla ROL
CREATE TABLE FIDE_ROL_TB (
    id_rol NUMBER PRIMARY KEY CONSTRAINT FIDE_ROL_ID_ROL_PK,
    nombre VARCHAR2(100) NOT NULL
);

-- 2. Tabla USUARIO
CREATE TABLE FIDE_USUARIO_TB (
    id_usuario NUMBER PRIMARY KEY CONSTRAINT FIDE_USUARIO_ID_USUARIO_PK,
    nombre VARCHAR2(100) NOT NULL,
    correo VARCHAR2(150) UNIQUE NOT NULL,
    contrasena VARCHAR2(150) NOT NULL,
    id_rol NUMBER REFERENCES FIDE_ROL_TB(id_rol)
);

-- 3. Tabla CATEGORIA
CREATE TABLE FIDE_CATEGORIA_TB (
    id_categoria NUMBER PRIMARY KEY CONSTRAINT FIDE_CATEGORIA_ID_CATEGORIA_PK,
    nombre VARCHAR2(100) NOT NULL
);

-- 4. Tabla UNIDAD_MEDIDA
CREATE TABLE FIDE_UNIDAD_MEDIDA_TB (
    id_unidad_medida NUMBER PRIMARY KEY CONSTRAINT FIDE_UNIDAD_MEDIDA_ID_UNIDAD_MEDIDA_PK,
    nombre VARCHAR2(100) NOT NULL
);

-- 5. Tabla PRODUCTO
CREATE TABLE FIDE_PRODUCTO_TB (
    id_producto NUMBER PRIMARY KEY CONSTRAINT FIDE_PRODUCTO_ID_PRODUCTO_PK,
    nombre VARCHAR2(100) NOT NULL,
    descripcion VARCHAR2(255),
    precio NUMBER(10,2) NOT NULL,
    id_categoria NUMBER REFERENCES FIDE_CATEGORIA_TB(id_categoria),
    id_unidad_medida NUMBER REFERENCES FIDE_UNIDAD_MEDIDA_TB(id_unidad_medida)
);

-- 6. Tabla CLIENTE
CREATE TABLE FIDE_CLIENTE_TB (
    id_cliente NUMBER PRIMARY KEY CONSTRAINT FIDE_CLIENTE_ID_CLIENTE_PK,
    nombre VARCHAR2(100) NOT NULL,
    correo VARCHAR2(150) UNIQUE,
    telefono VARCHAR2(15)
);

-- 7. Tabla DIRECCION
CREATE TABLE FIDE_DIRECCION_TB (
    id_direccion NUMBER PRIMARY KEY CONSTRAINT FIDE_DIRECCION_ID_DIRECCION_PK,
    id_cliente NUMBER REFERENCES FIDE_CLIENTE_TB(id_cliente),
    direccion VARCHAR2(255) NOT NULL
);

-- 8. Tabla PROVINCIA
CREATE TABLE FIDE_PROVINCIA_TB (
    id_provincia NUMBER PRIMARY KEY CONSTRAINT FIDE_PROVINCIA_ID_PROVINCIA_PK,
    nombre VARCHAR2(100) NOT NULL
);

-- 9. Tabla CANTON
CREATE TABLE FIDE_CANTON_TB (
    id_canton NUMBER PRIMARY KEY CONSTRAINT FIDE_CANTON_ID_CANTON_PK,
    id_provincia NUMBER REFERENCES FIDE_PROVINCIA_TB(id_provincia),
    nombre VARCHAR2(100) NOT NULL
);

-- 10. Tabla DISTRITO
CREATE TABLE FIDE_DISTRITO_TB (
    id_distrito NUMBER PRIMARY KEY CONSTRAINT FIDE_DISTRITO_ID_DISTRITO_PK,
    id_canton NUMBER REFERENCES FIDE_CANTON_TB(id_canton),
    nombre VARCHAR2(100) NOT NULL
);

-- 11. Tabla PEDIDO
CREATE TABLE FIDE_PEDIDO_TB (
    id_pedido NUMBER PRIMARY KEY CONSTRAINT FIDE_PEDIDO_ID_PEDIDO_PK,
    fecha_pedido DATE NOT NULL,
    cantidad NUMBER NOT NULL,
    precio_unitario NUMBER(10,2) NOT NULL,
    subtotal NUMBER(10,2) NOT NULL,
    total NUMBER(10,2) NOT NULL,
    id_factura NUMBER,
    id_producto NUMBER REFERENCES FIDE_PRODUCTO_TB(id_producto),
    id_estado NUMBER REFERENCES FIDE_ESTADO_PEDIDO_TB(id_estado),
    id_usuario NUMBER REFERENCES FIDE_USUARIO_TB(id_usuario),
    id_cliente NUMBER REFERENCES FIDE_CLIENTE_TB(id_cliente),
    id_direccion NUMBER REFERENCES FIDE_DIRECCION_TB(id_direccion)
);

-- 12. Tabla ESTADO_PEDIDO
CREATE TABLE FIDE_ESTADO_PEDIDO_TB (
    id_estado NUMBER PRIMARY KEY CONSTRAINT FIDE_ESTADO_PEDIDO_ID_ESTADO_PK,
    nombre VARCHAR2(100) NOT NULL
);

-- 13. Tabla INGRESO
CREATE TABLE FIDE_INGRESO_TB (
    id_ingreso NUMBER PRIMARY KEY CONSTRAINT FIDE_INGRESO_ID_INGRESO_PK,
    id_producto NUMBER REFERENCES FIDE_PRODUCTO_TB(id_producto),
    cantidad NUMBER NOT NULL,
    fecha DATE NOT NULL
);

-- 14. Tabla EGRESO
CREATE TABLE FIDE_EGRESO_TB (
    id_egreso NUMBER PRIMARY KEY CONSTRAINT FIDE_EGRESO_ID_EGRESO_PK,
    id_producto NUMBER REFERENCES FIDE_PRODUCTO_TB(id_producto),
    cantidad NUMBER NOT NULL,
    fecha DATE NOT NULL
);

-- 15. Tabla INSUMO
CREATE TABLE FIDE_INSUMO_TB (
    id_insumo NUMBER PRIMARY KEY CONSTRAINT FIDE_INSUMO_ID_INSUMO_PK,
    nombre VARCHAR2(100) NOT NULL,
    descripcion VARCHAR2(255),
    id_unidad_medida NUMBER REFERENCES FIDE_UNIDAD_MEDIDA_TB(id_unidad_medida)
);

-- 16. Tabla PROVEEDOR
CREATE TABLE FIDE_PROVEEDOR_TB (
    id_proveedor NUMBER PRIMARY KEY CONSTRAINT FIDE_PROVEEDOR_ID_PROVEEDOR_PK,
    nombre VARCHAR2(100) NOT NULL,
    correo VARCHAR2(150) UNIQUE,
    telefono VARCHAR2(15)
);

-- 17. Tabla ORDEN_COMPRA
CREATE TABLE FIDE_ORDEN_COMPRA_TB (
    id_orden_compra NUMBER PRIMARY KEY CONSTRAINT FIDE_ORDEN_COMPRA_ID_ORDEN_COMPRA_PK,
    id_proveedor NUMBER REFERENCES FIDE_PROVEEDOR_TB(id_proveedor),
    fecha DATE NOT NULL,
    total NUMBER(10,2) NOT NULL
);

-- 18. Tabla PRODUCTO_INSUMO
CREATE TABLE FIDE_PRODUCTO_INSUMO_TB (
    id_producto_insumo NUMBER PRIMARY KEY CONSTRAINT FIDE_PRODUCTO_INSUMO_ID_PRODUCTO_INSUMO_PK,
    id_producto NUMBER REFERENCES FIDE_PRODUCTO_TB(id_producto),
    id_insumo NUMBER REFERENCES FIDE_INSUMO_TB(id_insumo)
);

-- 19. Tabla TIPO_EDIFICIO
CREATE TABLE FIDE_TIPO_EDIFICIO_TB (
    id_tipo_edificio NUMBER PRIMARY KEY CONSTRAINT FIDE_TIPO_EDIFICIO_ID_TIPO_EDIFICIO_PK,
    nombre VARCHAR2(100) NOT NULL
);
