--Funciones
-- Función 1: Obtener el precio de un producto
CREATE OR REPLACE FUNCTION FIDE_PRODUCTO_OBTENER_PRECIO_FN (P_ID_PRODUCTO NUMBER)
RETURN NUMBER
IS
    V_PRECIO NUMBER;
BEGIN
    SELECT precio INTO V_PRECIO
    FROM FIDE_PRODUCTO_TB
    WHERE id_producto = P_ID_PRODUCTO;
    RETURN V_PRECIO;
END;
/
-- Función 2: Calcular el total de un pedido (cantidad * precio unitario)
CREATE OR REPLACE FUNCTION FIDE_PEDIDO_CALCULAR_TOTAL_FN (P_CANTIDAD NUMBER, P_PRECIO_UNITARIO NUMBER)
RETURN NUMBER
IS
    V_TOTAL NUMBER;
BEGIN
    V_TOTAL := P_CANTIDAD * P_PRECIO_UNITARIO;
    RETURN V_TOTAL;
END;
/
-- Función 3: Obtener el nombre de un cliente
CREATE OR REPLACE FUNCTION FIDE_CLIENTE_OBTENER_NOMBRE_FN (P_ID_CLIENTE NUMBER)
RETURN VARCHAR2
IS
    V_NOMBRE VARCHAR2(100);
BEGIN
    SELECT nombre INTO V_NOMBRE
    FROM FIDE_CLIENTE_TB
    WHERE id_cliente = P_ID_CLIENTE;
    RETURN V_NOMBRE;
END;
/
-- Función 4: Obtener el nombre de un producto
CREATE OR REPLACE FUNCTION FIDE_PRODUCTO_OBTENER_NOMBRE_FN (P_ID_PRODUCTO NUMBER)
RETURN VARCHAR2
IS
    V_NOMBRE VARCHAR2(100);
BEGIN
    SELECT nombre INTO V_NOMBRE
    FROM FIDE_PRODUCTO_TB
    WHERE id_producto = P_ID_PRODUCTO;
    RETURN V_NOMBRE;
END;
/
-- Función 5: Obtener el stock total de un producto
CREATE OR REPLACE FUNCTION FIDE_PRODUCTO_OBTENER_STOCK_FN (P_ID_PRODUCTO NUMBER)
RETURN NUMBER
IS
    V_STOCK NUMBER;
BEGIN
    SELECT 
        (SELECT NVL(SUM(cantidad), 0) FROM FIDE_INGRESO_TB WHERE id_producto = P_ID_PRODUCTO) -
        (SELECT NVL(SUM(cantidad), 0) FROM FIDE_EGRESO_TB WHERE id_producto = P_ID_PRODUCTO)
    INTO V_STOCK
    FROM DUAL;
    RETURN V_STOCK;
END;
/
-- Función 6: Obtener la dirección de un cliente
CREATE OR REPLACE FUNCTION FIDE_CLIENTE_OBTENER_DIRECCION_FN (P_ID_CLIENTE NUMBER)
RETURN VARCHAR2
IS
    V_DIRECCION VARCHAR2(255);
BEGIN
    SELECT direccion INTO V_DIRECCION
    FROM FIDE_DIRECCION_TB
    WHERE id_cliente = P_ID_CLIENTE;
    RETURN V_DIRECCION;
END;
/
-- Función 7: Verificar si un usuario existe
CREATE OR REPLACE FUNCTION FIDE_USUARIO_EXISTE_FN (P_CORREO VARCHAR2)
RETURN NUMBER
IS
    V_COUNT NUMBER;
BEGIN
    SELECT COUNT(*) INTO V_COUNT
    FROM FIDE_USUARIO_TB
    WHERE correo = P_CORREO;
    RETURN V_COUNT;
END;
/
-- Función 8: Calcular el subtotal de un pedido
CREATE OR REPLACE FUNCTION FIDE_PEDIDO_CALCULAR_SUBTOTAL_FN (P_CANTIDAD NUMBER, P_PRECIO_UNITARIO NUMBER)
RETURN NUMBER
IS
    V_SUBTOTAL NUMBER;
BEGIN
    V_SUBTOTAL := P_CANTIDAD * P_PRECIO_UNITARIO;
    RETURN V_SUBTOTAL;
END;
/
-- Función 9: Obtener el rol de un usuario
CREATE OR REPLACE FUNCTION FIDE_USUARIO_OBTENER_ROL_FN (P_ID_USUARIO NUMBER)
RETURN VARCHAR2
IS
    V_NOMBRE_ROL VARCHAR2(100);
BEGIN
    SELECT R.nombre INTO V_NOMBRE_ROL
    FROM FIDE_USUARIO_TB U
    INNER JOIN FIDE_ROL_TB R ON U.id_rol = R.id_rol
    WHERE U.id_usuario = P_ID_USUARIO;
    RETURN V_NOMBRE_ROL;
END;
/
-- Función 10: Contar los productos en una categoría
CREATE OR REPLACE FUNCTION FIDE_CATEGORIA_CONTAR_PRODUCTOS_FN (P_ID_CATEGORIA NUMBER)
RETURN NUMBER
IS
    V_COUNT NUMBER;
BEGIN
    SELECT COUNT(*) INTO V_COUNT
    FROM FIDE_PRODUCTO_TB
    WHERE id_categoria = P_ID_CATEGORIA;
    RETURN V_COUNT;
END;
/
-- Función 11: Calcular el total de una orden de compra
CREATE OR REPLACE FUNCTION FIDE_ORDEN_CALCULAR_TOTAL_FN (P_ID_ORDEN_COMPRA NUMBER)
RETURN NUMBER
IS
    V_TOTAL NUMBER;
BEGIN
    SELECT total INTO V_TOTAL
    FROM FIDE_ORDEN_COMPRA_TB
    WHERE id_orden_compra = P_ID_ORDEN_COMPRA;
    RETURN V_TOTAL;
END;
/
-- Función 12: Obtener el proveedor de una orden de compra
CREATE OR REPLACE FUNCTION FIDE_ORDEN_OBTENER_PROVEEDOR_FN (P_ID_ORDEN_COMPRA NUMBER)
RETURN VARCHAR2
IS
    V_NOMBRE_PROVEEDOR VARCHAR2(100);
BEGIN
    SELECT P.nombre INTO V_NOMBRE_PROVEEDOR
    FROM FIDE_ORDEN_COMPRA_TB OC
    INNER JOIN FIDE_PROVEEDOR_TB P ON OC.id_proveedor = P.id_proveedor
    WHERE OC.id_orden_compra = P_ID_ORDEN_COMPRA;
    RETURN V_NOMBRE_PROVEEDOR;
END;
/
-- Función 13: Verificar disponibilidad de stock
CREATE OR REPLACE FUNCTION FIDE_PRODUCTO_STOCK_DISPONIBLE_FN (P_ID_PRODUCTO NUMBER, P_CANTIDAD NUMBER)
RETURN VARCHAR2
IS
    V_STOCK NUMBER;
BEGIN
    V_STOCK := FIDE_PRODUCTO_OBTENER_STOCK_FN(P_ID_PRODUCTO);
    IF V_STOCK >= P_CANTIDAD THEN
        RETURN 'STOCK DISPONIBLE';
    ELSE
        RETURN 'STOCK INSUFICIENTE';
    END IF;
END;
/
-- Función 14: Obtener el nombre de una categoría
CREATE OR REPLACE FUNCTION FIDE_CATEGORIA_OBTENER_NOMBRE_FN (P_ID_CATEGORIA NUMBER)
RETURN VARCHAR2
IS
    V_NOMBRE VARCHAR2(100);
BEGIN
    SELECT nombre INTO V_NOMBRE
    FROM FIDE_CATEGORIA_TB
    WHERE id_categoria = P_ID_CATEGORIA;
    RETURN V_NOMBRE;
END;
/
-- Función 15: Obtener el nombre de una unidad de medida
CREATE OR REPLACE FUNCTION FIDE_UNIDAD_MEDIDA_OBTENER_NOMBRE_FN (P_ID_UNIDAD_MEDIDA NUMBER)
RETURN VARCHAR2
IS
    V_NOMBRE VARCHAR2(100);
BEGIN
    SELECT nombre INTO V_NOMBRE
    FROM FIDE_UNIDAD_MEDIDA_TB
    WHERE id_unidad_medida = P_ID_UNIDAD_MEDIDA;
    RETURN V_NOMBRE;
END;
/