/
CREATE OR REPLACE TRIGGER FIDE_VALIDAR_PRECIO_PRODUCTO_TRG
BEFORE INSERT OR UPDATE ON FIDE_PRODUCTO_TB
FOR EACH ROW
BEGIN
    IF :NEW.precio < 0 THEN
        RAISE_APPLICATION_ERROR(-20001, 'El precio del producto no puede ser negativo.');
    END IF;
END;
/
CREATE OR REPLACE TRIGGER FIDE_VALIDAR_CANTIDAD_PEDIDO_TRG
BEFORE INSERT OR UPDATE ON FIDE_PEDIDO_TB
FOR EACH ROW
BEGIN
    IF :NEW.cantidad <= 0 THEN
        RAISE_APPLICATION_ERROR(-20002, 'La cantidad del pedido debe ser mayor que cero.');
    END IF;
END;
/
CREATE OR REPLACE TRIGGER FIDE_VALIDAR_TOTAL_ORDEN_TRG
BEFORE INSERT OR UPDATE ON FIDE_ORDEN_COMPRA_TB
FOR EACH ROW
BEGIN
    IF :NEW.total <= 0 THEN
        RAISE_APPLICATION_ERROR(-20003, 'El total de la orden de compra debe ser mayor que cero.');
    END IF;
END;
/
CREATE OR REPLACE TRIGGER FIDE_VALIDAR_TELEFONO_CLIENTE_TRG
BEFORE INSERT OR UPDATE ON FIDE_CLIENTE_TB
FOR EACH ROW
BEGIN
    IF REGEXP_LIKE(:NEW.telefono, '[^0-9]') THEN
        RAISE_APPLICATION_ERROR(-20004, 'El teléfono del cliente debe contener solo números.');
    END IF;
END;
/
CREATE OR REPLACE TRIGGER FIDE_VALIDAR_CORREO_USUARIO_TRG
BEFORE INSERT OR UPDATE ON FIDE_USUARIO_TB
FOR EACH ROW
BEGIN
    IF NOT REGEXP_LIKE(:NEW.correo, '@') THEN
        RAISE_APPLICATION_ERROR(-20007, 'El correo del usuario debe contener "@".');
    END IF;
END;
/